"""
backtest_historical.py
──────────────────────
Backtesting using real Curve 3Pool swap data (Dune Analytics).

Data:
  data/raw/curve3pool_swaps_svb.csv   (2023-03-09 ~ 03-14)
  data/raw/curve3pool_swaps_usdt.csv  (2023-06-14 ~ 06-16)

Strategy ①: AMM reverse swap
  Execute a single Curve 3Pool swap at the moment of peak pool imbalance.
  Uses VWAP implied execution price from real settlement data.

Strategy ②: Anticipation position
  Pool imbalance threshold signal → early entry.
  Net return calculated after Aave borrowing cost.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Usage
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  python -m src.scripts.backtest_historical

Prerequisites — the following CSVs must exist or an error will occur:
  data/raw/curve3pool_swaps_svb.csv    ← generated by running fetch_dune.py
  data/raw/curve3pool_swaps_usdt.csv   ← generated by running fetch_dune.py

  Fetch data:  python -m src.fetch_dune  (requires DUNE_API_KEY in .env)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Configurable constants (top of file)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  INITIAL_RESERVES    : pool reserve baseline just before each event (USD)
  AAVE_APR            : Strategy ② Aave borrow rate (normal 5%, crisis 60%)
  CRISIS_THRESHOLD    : pool share (%) above which crisis rate applies (default 65.0)
  DEFAULT_THRESHOLDS  : Strategy ② entry signal thresholds per event
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

import pandas as pd
import numpy as np
from pathlib import Path

# ── Path configuration ────────────────────────────────────────────────────────

DATA_DIR = Path(__file__).parent.parent.parent / "data" / "raw"

# ── Per-event configuration ───────────────────────────────────────────────────

# Approximate pool reserves just before each event (from fetch_dune.py compute_pool_composition)
# SVB:  2023-03-09 — USDC was already lower than USDT/DAI
# USDT: 2023-06-14 — USDT slightly higher than USDC/DAI
INITIAL_RESERVES: dict[str, dict[str, float]] = {
    "svb":  {"DAI": 500_000_000, "USDC": 350_000_000, "USDT": 500_000_000},
    "usdt": {"DAI": 160_000_000, "USDC": 160_000_000, "USDT": 200_000_000},
}

# Trade direction per event: (token to sell, token to buy) — buy the cheaper depegged token
TARGET_PAIR: dict[str, tuple[str, str]] = {
    "svb":  ("USDT", "USDC"),   # USDC falls → sell USDT, buy cheap USDC
    "usdt": ("USDC", "USDT"),   # USDT falls → sell USDC, buy cheap USDT
}

# Depegged token (the one whose pool share we track)
TARGET_TOKEN: dict[str, str] = {
    "svb":  "USDC",
    "usdt": "USDT",
}

# Aave annual borrow rate — elevated during crisis periods
AAVE_APR = {
    "normal": 0.05,   # 5% APR (normal conditions)
    "crisis": 0.60,   # 60% APR (depeg panic)
}

# Pool share above this level triggers crisis borrow rate
CRISIS_THRESHOLD = 65.0

# Strategy ② entry thresholds per event
# SVB:  USDC only rose to ~44% — use lower thresholds
# USDT: USDT rose to ~63% — use mid-range thresholds
DEFAULT_THRESHOLDS: dict[str, list[float]] = {
    "svb":  [33.0, 35.0, 38.0, 40.0, 42.0],
    "usdt": [45.0, 50.0, 55.0, 60.0, 63.0],
}


# ── Data loading ──────────────────────────────────────────────────────────────

def load_data(event_name: str) -> pd.DataFrame:
    """
    Load Curve 3Pool swap CSV for the given event.

    Returns
    -------
    DataFrame: hour(datetime), token_sold_symbol, token_bought_symbol,
               sold_amount, bought_amount, trade_count
    """
    path = DATA_DIR / f"curve3pool_swaps_{event_name}.csv"
    df = pd.read_csv(path, parse_dates=["hour"])
    return df.sort_values("hour").reset_index(drop=True)


# ── Pool composition reconstruction ──────────────────────────────────────────

def reconstruct_pool_composition(
    df:         pd.DataFrame,
    event_name: str,
) -> pd.DataFrame:
    """
    Reconstruct hourly pool composition ratios by accumulating swap flows.

    On each swap:
      - token_sold (deposited) reserve increases
      - token_bought (withdrawn) reserve decreases

    Parameters
    ----------
    df         : result of load_data()
    event_name : "svb" or "usdt"

    Returns
    -------
    DataFrame: hour, dai_pct, usdc_pct, usdt_pct, total_tvl
    """
    reserves = {k: float(v) for k, v in INITIAL_RESERVES[event_name].items()}
    records  = []

    for hour, hour_df in df.groupby("hour", sort=True):
        # Apply each swap's net flow
        for _, row in hour_df.iterrows():
            t_in  = row["token_sold_symbol"]    # token entering the pool
            t_out = row["token_bought_symbol"]  # token leaving the pool

            if t_in  in reserves:
                reserves[t_in]  += row["sold_amount"]
            if t_out in reserves:
                reserves[t_out] -= row["bought_amount"]
                reserves[t_out]  = max(reserves[t_out], 0.0)  # prevent negative

        total = sum(reserves.values())
        records.append({
            "hour":      hour,
            "dai_pct":   reserves["DAI"]  / total * 100,
            "usdc_pct":  reserves["USDC"] / total * 100,
            "usdt_pct":  reserves["USDT"] / total * 100,
            "total_tvl": total,
        })

    return pd.DataFrame(records)


# ── Implied execution price calculation ──────────────────────────────────────

def compute_hourly_prices(
    df:         pd.DataFrame,
    event_name: str,
) -> pd.DataFrame:
    """
    Compute hourly VWAP (volume-weighted average price) implied execution price
    from real swap data.

    implied_price = sold_amount / bought_amount
      → amount of the sell token paid per unit of the target token received
      → lower value = target token is cheaper (deeper depeg)

    Parameters
    ----------
    df         : result of load_data()
    event_name : "svb" or "usdt"

    Returns
    -------
    DataFrame: hour, implied_price (VWAP), volume
    """
    sold_sym, bought_sym = TARGET_PAIR[event_name]

    mask  = (df["token_sold_symbol"] == sold_sym) & (df["token_bought_symbol"] == bought_sym)
    swaps = df[mask].copy()

    if swaps.empty:
        return pd.DataFrame(columns=["hour", "implied_price", "volume"])

    swaps["implied_price"] = swaps["sold_amount"] / swaps["bought_amount"]
    swaps["weighted"]      = swaps["implied_price"] * swaps["sold_amount"]

    hourly = (
        swaps
        .groupby("hour", sort=True)
        .agg(volume=("sold_amount", "sum"), weighted_sum=("weighted", "sum"))
        .reset_index()
    )
    hourly["implied_price"] = hourly["weighted_sum"] / hourly["volume"]

    return hourly[["hour", "implied_price", "volume"]]


def _get_price_at(price_df: pd.DataFrame, target_hour: pd.Timestamp) -> float:
    """
    Return the nearest implied price at or before target_hour.
    Falls back to the earliest available price if no prior data exists.
    """
    before = price_df[price_df["hour"] <= target_hour]
    if not before.empty:
        return float(before.iloc[-1]["implied_price"])
    after = price_df[price_df["hour"] > target_hour]
    if not after.empty:
        return float(after.iloc[0]["implied_price"])
    return 1.0  # assume peg if no data available


def _hours_to_recovery(
    composition_df: pd.DataFrame,
    from_hour:      pd.Timestamp,
    target_pct_col: str,
    recovery_level: float = 40.0,
) -> int:
    """
    Hours from from_hour until the pool share drops back to recovery_level or below.
    Returns the remaining dataset length if recovery never occurs.
    """
    after    = composition_df[composition_df["hour"] >= from_hour]
    recovery = after[after[target_pct_col] <= recovery_level]

    if not recovery.empty:
        end_hour = recovery.iloc[0]["hour"]
    else:
        end_hour = composition_df.iloc[-1]["hour"]

    delta = end_hour - from_hour
    return max(1, int(delta.total_seconds() / 3600))


# ── Strategy ① backtest ───────────────────────────────────────────────────────

def backtest_strategy1(
    composition_df: pd.DataFrame,
    price_df:       pd.DataFrame,
    event_name:     str,
    amount_usd:     float = 50_000,
) -> dict:
    """
    Strategy ①: AMM reverse swap

    Execute a single swap at the moment of peak pool imbalance.
    Uses Curve 3Pool only — no aggregator.

    Parameters
    ----------
    composition_df : result of reconstruct_pool_composition()
    price_df       : result of compute_hourly_prices()
    event_name     : "svb" or "usdt"
    amount_usd     : trade size (USD)

    Returns
    -------
    dict: entry time, pool share at entry, execution price, tokens received,
          return %, holding hours
    """
    target         = TARGET_TOKEN[event_name]
    target_pct_col = f"{target.lower()}_pct"

    # Find peak imbalance moment
    peak_idx  = composition_df[target_pct_col].idxmax()
    peak_row  = composition_df.loc[peak_idx]
    peak_hour = peak_row["hour"]

    # Implied execution price at that moment
    entry_price = _get_price_at(price_df, peak_hour)

    # Tokens received and profit
    target_received = amount_usd / entry_price          # target tokens acquired
    proceeds        = target_received * 1.00            # sell at $1.00 after recovery
    gross_pnl_pct   = (proceeds - amount_usd) / amount_usd * 100

    # Holding period (until pool share drops back to 40%)
    holding_hours = _hours_to_recovery(composition_df, peak_hour, target_pct_col)

    return {
        "strategy":      "① Reverse Swap",
        "event":         event_name.upper(),
        "entry_hour":    str(peak_hour),
        "pool_composition": (
            f"DAI {peak_row['dai_pct']:.1f}% / "
            f"USDC {peak_row['usdc_pct']:.1f}% / "
            f"USDT {peak_row['usdt_pct']:.1f}%"
        ),
        "entry_price":       round(entry_price, 4),
        "target_received":   round(target_received, 2),
        "gross_pnl_pct":     round(gross_pnl_pct, 2),
        "borrow_cost_pct":   0.0,
        "net_pnl_pct":       round(gross_pnl_pct, 2),
        "holding_hours":     holding_hours,
        "note":              "Direct swap — no borrowing required",
    }


# ── Strategy ② backtest ───────────────────────────────────────────────────────

def backtest_strategy2(
    composition_df: pd.DataFrame,
    price_df:       pd.DataFrame,
    event_name:     str,
    thresholds:     list[float] | None = None,
    amount_usd:     float = 50_000,
) -> pd.DataFrame:
    """
    Strategy ②: Anticipation position

    Enter when pool imbalance crosses a threshold — before peak depeg.
    Structure: ETH collateral → borrow "safe" stablecoin on Aave → buy depegged token.
      SVB  case: ETH collateral → borrow USDT → buy cheap USDC
      USDT case: ETH collateral → borrow USDC → buy cheap USDT
    Net return calculated after Aave borrow interest.

    Parameters
    ----------
    composition_df : result of reconstruct_pool_composition()
    price_df       : result of compute_hourly_prices()
    event_name     : "svb" or "usdt"
    thresholds     : list of pool share thresholds to test
    amount_usd     : trade size (USD)

    Returns
    -------
    DataFrame: entry time, execution price, return, borrow cost, net return per threshold
    """
    if thresholds is None:
        thresholds = DEFAULT_THRESHOLDS[event_name]

    target         = TARGET_TOKEN[event_name]
    target_pct_col = f"{target.lower()}_pct"
    results        = []

    for threshold in thresholds:
        signal_rows = composition_df[composition_df[target_pct_col] >= threshold]

        if signal_rows.empty:
            results.append({
                "threshold":         threshold,
                "signal_triggered":  False,
                "entry_hour":        None,
                "pool_pct_at_entry": None,
                "entry_price":       None,
                "holding_hours":     0,
                "gross_pnl_pct":     0.0,
                "borrow_cost_pct":   0.0,
                "net_pnl_pct":       0.0,
            })
            continue

        entry_hour = signal_rows.iloc[0]["hour"]
        entry_row  = signal_rows.iloc[0]
        entry_pct  = entry_row[target_pct_col]

        entry_price = _get_price_at(price_df, entry_hour)

        # Return: buy target token at entry price → sell at $1.00 on recovery
        gross_pnl_pct = (1.0 - entry_price) / entry_price * 100

        # Holding period
        holding_hours = _hours_to_recovery(composition_df, entry_hour, target_pct_col)

        # Aave borrow cost (crisis rate applies above CRISIS_THRESHOLD)
        apr             = AAVE_APR["crisis"] if entry_pct >= CRISIS_THRESHOLD else AAVE_APR["normal"]
        borrow_cost_pct = apr / 365 / 24 * holding_hours * 100

        net_pnl_pct = gross_pnl_pct - borrow_cost_pct

        results.append({
            "threshold":        threshold,
            "signal_triggered": True,
            "entry_hour":       str(entry_hour),
            "pool_composition": (
                f"DAI {entry_row['dai_pct']:.1f}% / "
                f"USDC {entry_row['usdc_pct']:.1f}% / "
                f"USDT {entry_row['usdt_pct']:.1f}%"
            ),
            "entry_price":      round(entry_price, 4),
            "holding_hours":    holding_hours,
            "gross_pnl_pct":    round(gross_pnl_pct, 2),
            "borrow_cost_pct":  round(borrow_cost_pct, 4),
            "net_pnl_pct":      round(net_pnl_pct, 2),
        })

    return pd.DataFrame(results)


# ── Main runner ───────────────────────────────────────────────────────────────

def run_backtest(event_name: str, amount_usd: float = 50_000) -> dict:
    """
    Run Strategy ① and ② backtests for a given event and print results.

    Parameters
    ----------
    event_name : "svb" or "usdt"
    amount_usd : trade size (USD)

    Returns
    -------
    dict:
      "strategy1"   : Strategy ① result dict
      "strategy2"   : Strategy ② result DataFrame
      "composition" : hourly pool composition DataFrame
      "prices"      : hourly implied price DataFrame
    """
    print(f"\n{'='*64}")
    print(f"  {event_name.upper()} Event Backtest  (Trade size: ${amount_usd:,.0f})")
    print(f"{'='*64}")

    df          = load_data(event_name)
    composition = reconstruct_pool_composition(df, event_name)
    prices      = compute_hourly_prices(df, event_name)

    target     = TARGET_TOKEN[event_name]
    pct_col    = f"{target.lower()}_pct"
    peak_pct   = composition[pct_col].max()
    peak_hour  = composition.loc[composition[pct_col].idxmax(), "hour"]
    min_price  = prices["implied_price"].min() if not prices.empty else float("nan")

    print(f"\n[Data Summary]")
    print(f"  Period            : {df['hour'].min()} ~ {df['hour'].max()}")
    print(f"  {target} peak share : {peak_pct:.1f}%  ({peak_hour})")
    print(f"  Lowest fill price : ${min_price:.4f}")

    s1 = backtest_strategy1(composition, prices, event_name, amount_usd)

    print(f"\n[Strategy ① — Reverse Swap Results]")
    for k, v in s1.items():
        print(f"  {k:<22}: {v}")

    s2 = backtest_strategy2(composition, prices, event_name, amount_usd=amount_usd)

    print(f"\n[Strategy ② — Anticipation Position Results]")
    cols = ["threshold", "pool_composition", "entry_price",
            "holding_hours", "gross_pnl_pct", "borrow_cost_pct", "net_pnl_pct"]
    print(s2[cols].to_string(index=False))

    return {
        "strategy1":   s1,
        "strategy2":   s2,
        "composition": composition,
        "prices":      prices,
    }


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    svb_result  = run_backtest("svb",  amount_usd=50_000)
    usdt_result = run_backtest("usdt", amount_usd=50_000)

    # Cross-event Strategy ② comparison
    print(f"\n{'='*64}")
    print("  Strategy ② Cross-Event Comparison")
    print(f"{'='*64}")
    for name, res in [("SVB", svb_result), ("USDT", usdt_result)]:
        best = res["strategy2"][res["strategy2"]["signal_triggered"] == True]
        if not best.empty:
            r = best.loc[best["net_pnl_pct"].idxmax()]
            print(f"  {name}: threshold {r['threshold']}%  entry ${r['entry_price']:.4f}  "
                  f"net return {r['net_pnl_pct']:.2f}%  holding {r['holding_hours']}h")


# ── Backtest Results Summary (as of 2025-03 / $50,000 trade size) ─────────────
#
# ┌──────────────────────────────────────────────────────────────────────────────┐
# │  SVB Crisis (2023-03-09 ~ 03-14)  |  Depegged token: USDC                  │
# │  Lowest fill price: $0.8849                                                  │
# ├──────────────────────────────────────────────────────────────────────────────┤
# │  Strategy ①  Reverse Swap  (single entry at peak)                           │
# │    Pool:  DAI 30.8% / USDC 44.0% / USDT 25.2%                              │
# │    Price: $0.9391  |  Received: 53,245 USDC  |  Net: +6.49%  |  Hold: 4h   │
# │                                                                              │
# │  Strategy ②  Anticipation  (ETH collateral → borrow USDT → buy cheap USDC) │
# │    threshold  Pool (DAI / USDC / USDT)               entry    hold  net     │
# │    33%        DAI 40.7% / USDC 33.4% / USDT 26.0%   $0.9392   1h  +6.47%  │
# │    35%        DAI 38.7% / USDC 35.6% / USDT 25.7%   $0.9121   1h  +9.63%  │
# │    38%  ★    DAI 35.4% / USDC 39.0% / USDT 25.7%   $0.8849   1h +13.01%  │
# │    40%        DAI 32.4% / USDC 41.8% / USDT 25.9%   $0.9012  15h +10.95%  │
# │    42%        DAI 31.1% / USDC 42.9% / USDT 26.0%   $0.9130  14h  +9.53%  │
# │                                                                              │
# │  [Interpretation] Anticipation outperforms reverse swap by ~2x.             │
# │  USDC price crashed first, pool imbalance followed as a lagging signal.     │
# │  38% threshold captured the lowest price ($0.8849). USDT share stayed       │
# │  stable at 25~26% while DAI share dropped — users fled USDC to both        │
# │  DAI and USDT simultaneously. Borrow cost negligible at 1-hour hold.        │
# └──────────────────────────────────────────────────────────────────────────────┘
#
# ┌──────────────────────────────────────────────────────────────────────────────┐
# │  USDT Depeg (2023-06-14 ~ 06-16)  |  Depegged token: USDT                  │
# │  Lowest fill price: $0.9966                                                  │
# ├──────────────────────────────────────────────────────────────────────────────┤
# │  Strategy ①  Reverse Swap  (single entry at peak)                           │
# │    Pool:  DAI 18.9% / USDC 17.7% / USDT 63.4%                              │
# │    Price: $0.9981  |  Received: 50,096 USDT  |  Net: +0.19%  |  Hold: 42h  │
# │                                                                              │
# │  Strategy ②  Anticipation  (ETH collateral → borrow USDC → buy cheap USDT) │
# │    threshold  Pool (DAI / USDC / USDT)               entry    hold  net     │
# │    45%        DAI 28.8% / USDC 26.0% / USDT 45.2%   $0.9999  48h  -0.02%  │
# │    50%        DAI 27.2% / USDC 22.0% / USDT 50.9%   $0.9997  45h  +0.01%  │
# │    55%        DAI 23.6% / USDC 20.7% / USDT 55.7%   $0.9994  43h  +0.04%  │
# │    60%  ★    DAI 18.9% / USDC 17.7% / USDT 63.4%   $0.9981  42h  +0.17%  │
# │    63%        DAI 18.9% / USDC 17.7% / USDT 63.4%   $0.9981  42h  +0.17%  │
# │                                                                              │
# │  [Interpretation] Minor depeg ($0.004) → overall returns negligible.        │
# │  DAI and USDC depleted evenly while USDT accumulated — single-pressure      │
# │  structure. Early entry at 45% results in negative net return due to        │
# │  borrow cost exceeding gains (-0.02%). Unlike SVB, only entries near the    │
# │  peak (60%) yield meaningful returns. Earlier entry = worse outcome.        │
# └──────────────────────────────────────────────────────────────────────────────┘
