"""
split_swap_backtest.py
──────────────────────
Simple VWAP comparison backtest: Curve 3Pool vs Uniswap V3 USDC/USDT pool.

Data:
  data/raw/curve3pool_swaps_svb.csv     (2023-03-09 ~ 03-14)
  data/raw/curve3pool_swaps_usdt.csv    (2023-06-14 ~ 06-16)
  data/raw/uniswap_swaps_svb.csv        (2023-03-09 ~ 03-14)
  data/raw/uniswap_swaps_usdt.csv       (2023-06-14 ~ 06-16)

Comparison method (Option A: simple VWAP comparison):
  - Compute hourly VWAP (implied execution price) for both pools
  - Identify the more favorable pool per hour (lower implied_price = cheaper target token)
  - Strategy: (A) always use Curve vs (B) route to optimal pool each hour
  - Peak-period deep dive: price gap and improvement effect between pools

Metric:
  implied_price = sold_amount / bought_amount
    → amount of sell token paid per unit of target token received
    → lower = cheaper target token (more favorable fill)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Usage
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  python -m src.scripts.split_swap_backtest

Prerequisites — the following CSVs must exist or an error will occur:
  data/raw/curve3pool_swaps_svb.csv    ← generated by running fetch_dune.py
  data/raw/curve3pool_swaps_usdt.csv   ← generated by running fetch_dune.py
  data/raw/uniswap_swaps_svb.csv       ← generated by running fetch_dune.py
  data/raw/uniswap_swaps_usdt.csv      ← generated by running fetch_dune.py

  Fetch data:  python -m src.fetch_dune  (requires DUNE_API_KEY in .env)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Configurable constants (top of file)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  TARGET_PAIR   : trade direction per event (token to sell, token to buy)
  PEAK_POOL_PCT : peak pool composition label (reference only)

  Uniswap V3 pool address (as used in Dune SQL):
    USDC/USDT 0.01% fee: 0x3416cf6c708da44db2624d63ea0aaef7113527c6
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

import pandas as pd
from pathlib import Path

# ── Path configuration ────────────────────────────────────────────────────────

DATA_DIR = Path(__file__).parent.parent.parent / "data" / "raw"

# ── Per-event configuration ───────────────────────────────────────────────────

# Trade direction per event: (token to sell, token to buy)
TARGET_PAIR: dict[str, tuple[str, str]] = {
    "svb":  ("USDT", "USDC"),   # USDC falls → sell USDT, buy cheap USDC
    "usdt": ("USDC", "USDT"),   # USDT falls → sell USDC, buy cheap USDT
}

# Peak pool composition at depeg maximum (from backtest_historical.py results)
PEAK_POOL_PCT: dict[str, str] = {
    "svb":  "DAI 30.8% / USDC 44.0% / USDT 25.2%",
    "usdt": "DAI 18.9% / USDC 17.7% / USDT 63.4%",
}


# ── Data loading ──────────────────────────────────────────────────────────────

def load_pool_data(pool: str, event_name: str) -> pd.DataFrame:
    """
    Load swap CSV for the given pool and event.

    Parameters
    ----------
    pool       : "curve" or "uniswap"
    event_name : "svb" or "usdt"

    Returns
    -------
    DataFrame: hour(datetime), token_sold_symbol, token_bought_symbol,
               sold_amount, bought_amount, trade_count
    """
    filename = {
        "curve":   f"curve3pool_swaps_{event_name}.csv",
        "uniswap": f"uniswap_swaps_{event_name}.csv",
    }[pool]

    path = DATA_DIR / filename
    df   = pd.read_csv(path, parse_dates=["hour"])
    return df.sort_values("hour").reset_index(drop=True)


# ── VWAP calculation ──────────────────────────────────────────────────────────

def compute_vwap(df: pd.DataFrame, sold_sym: str, bought_sym: str) -> pd.DataFrame:
    """
    Compute hourly VWAP (volume-weighted average implied price).

    Parameters
    ----------
    df         : result of load_pool_data()
    sold_sym   : token deposited (e.g. "USDT")
    bought_sym : token received (e.g. "USDC")

    Returns
    -------
    DataFrame: hour, implied_price (VWAP), volume (sum of sold_amount), trade_count
    """
    mask  = (df["token_sold_symbol"] == sold_sym) & (df["token_bought_symbol"] == bought_sym)
    swaps = df[mask].copy()

    if swaps.empty:
        return pd.DataFrame(columns=["hour", "implied_price", "volume", "trade_count"])

    swaps["implied_price"] = swaps["sold_amount"] / swaps["bought_amount"]
    swaps["weighted"]      = swaps["implied_price"] * swaps["sold_amount"]

    hourly = (
        swaps
        .groupby("hour", sort=True)
        .agg(
            volume       = ("sold_amount",  "sum"),
            weighted_sum = ("weighted",     "sum"),
            trade_count  = ("trade_count",  "sum"),
        )
        .reset_index()
    )
    hourly["implied_price"] = hourly["weighted_sum"] / hourly["volume"]

    return hourly[["hour", "implied_price", "volume", "trade_count"]]


# ── Pool comparison ───────────────────────────────────────────────────────────

def compare_pools(event_name: str) -> pd.DataFrame:
    """
    Build a hourly Curve vs Uniswap VWAP comparison table.

    Only includes hours where both pools have data.
    better_pool: the pool with lower implied_price (more favorable fill).
    price_diff_bps: how much more expensive Curve is vs Uniswap (positive = Curve worse).

    Returns
    -------
    DataFrame: hour, curve_price, uni_price, curve_volume, uni_volume,
               better_pool, price_diff_bps
    """
    sold_sym, bought_sym = TARGET_PAIR[event_name]

    curve_df  = load_pool_data("curve",   event_name)
    uni_df    = load_pool_data("uniswap", event_name)

    curve_vwap = compute_vwap(curve_df,  sold_sym, bought_sym)
    uni_vwap   = compute_vwap(uni_df,    sold_sym, bought_sym)

    merged = pd.merge(
        curve_vwap.rename(columns={"implied_price": "curve_price",   "volume": "curve_volume",   "trade_count": "curve_trades"}),
        uni_vwap  .rename(columns={"implied_price": "uni_price",     "volume": "uni_volume",     "trade_count": "uni_trades"}),
        on="hour",
        how="inner",
    )

    merged["better_pool"]    = merged.apply(
        lambda r: "curve" if r["curve_price"] <= r["uni_price"] else "uniswap", axis=1
    )
    merged["price_diff_bps"] = (merged["curve_price"] - merged["uni_price"]) / merged["uni_price"] * 10_000

    return merged.reset_index(drop=True)


# ── Return calculation ────────────────────────────────────────────────────────

def calc_pnl(entry_price: float, amount_usd: float = 50_000) -> dict:
    """
    Compute gross return assuming recovery to $1.00 from entry_price.
    """
    received   = amount_usd / entry_price
    gross_pct  = (received * 1.00 - amount_usd) / amount_usd * 100
    return {
        "entry_price":   round(entry_price, 4),
        "received":      round(received, 2),
        "gross_pnl_pct": round(gross_pct, 2),
    }


# ── Main runner ───────────────────────────────────────────────────────────────

def run_comparison(event_name: str, amount_usd: float = 50_000) -> dict:
    """
    Run Curve vs Uniswap VWAP comparison for a given event and print results.

    Output sections:
      1. Hourly VWAP comparison table for both pools
      2. Peak period deep dive (±2h window)
      3. Optimal per-hour routing vs always-Curve improvement

    Returns
    -------
    dict:
      "comparison"   : hourly comparison DataFrame
      "peak_summary" : peak ±2h window DataFrame
      "routing"      : routing strategy returns dict
    """
    sold_sym, bought_sym = TARGET_PAIR[event_name]

    print(f"\n{'='*68}")
    print(f"  {event_name.upper()} Event  |  {sold_sym} → {bought_sym}  |  Curve vs Uniswap VWAP Comparison")
    print(f"{'='*68}")

    comp = compare_pools(event_name)

    if comp.empty:
        print("  No overlapping hours found between both pools.")
        return {}

    # ── 1. Hourly comparison table ────────────────────────────────────────────
    print(f"\n[Hourly VWAP Comparison]  (units: {sold_sym} paid per unit of {bought_sym})")
    print(f"  {'hour':<22}  {'curve':>8}  {'uni':>8}  {'diff(bps)':>10}  {'better':>8}")
    print(f"  {'-'*60}")
    for _, row in comp.iterrows():
        marker = " ★" if row["better_pool"] == "uniswap" else "  "
        print(
            f"  {str(row['hour']):<22}  "
            f"{row['curve_price']:>8.4f}  "
            f"{row['uni_price']:>8.4f}  "
            f"{row['price_diff_bps']:>+10.1f}  "
            f"{row['better_pool']:>8}{marker}"
        )

    # ── 2. Peak period analysis ───────────────────────────────────────────────
    # Peak: hour with lowest curve_price (deepest depeg)
    peak_idx  = comp["curve_price"].idxmin()
    peak_hour = comp.loc[peak_idx, "hour"]

    window_start = max(0, peak_idx - 2)
    window_end   = min(len(comp), peak_idx + 3)
    peak_window  = comp.iloc[window_start:window_end]

    print(f"\n[Peak Period Analysis]  peak hour = {peak_hour}")
    print(f"  Pool composition (from backtest_historical.py): {PEAK_POOL_PCT[event_name]}")
    print(f"\n  {'hour':<22}  {'curve':>8}  {'uni':>8}  {'diff(bps)':>10}  {'better':>8}")
    print(f"  {'-'*60}")
    for _, row in peak_window.iterrows():
        marker = " ◀" if row["hour"] == peak_hour else "  "
        print(
            f"  {str(row['hour']):<22}  "
            f"{row['curve_price']:>8.4f}  "
            f"{row['uni_price']:>8.4f}  "
            f"{row['price_diff_bps']:>+10.1f}  "
            f"{row['better_pool']:>8}{marker}"
        )

    peak_row   = comp.loc[peak_idx]
    curve_pnl  = calc_pnl(peak_row["curve_price"], amount_usd)
    uni_pnl    = calc_pnl(peak_row["uni_price"],   amount_usd)

    print(f"\n  Peak fill prices:")
    print(f"    Curve   : ${curve_pnl['entry_price']:.4f}  →  return {curve_pnl['gross_pnl_pct']:+.2f}%")
    print(f"    Uniswap : ${uni_pnl['entry_price']:.4f}  →  return {uni_pnl['gross_pnl_pct']:+.2f}%")
    improvement = uni_pnl["gross_pnl_pct"] - curve_pnl["gross_pnl_pct"]
    better      = "Uniswap" if peak_row["uni_price"] < peak_row["curve_price"] else "Curve"
    print(f"    Better pool   : {better}  (gap: {abs(peak_row['price_diff_bps']):.1f} bps)")
    print(f"    Return delta  : {improvement:+.2f}%p  (Uniswap vs Curve at peak)")

    # ── 3. Routing strategy comparison (full period average) ──────────────────
    curve_wins  = (comp["better_pool"] == "curve").sum()
    uni_wins    = (comp["better_pool"] == "uniswap").sum()
    total_hours = len(comp)

    avg_curve = comp["curve_price"].mean()
    avg_uni   = comp["uni_price"].mean()

    # Optimal routing: pick the lower-priced pool each hour
    comp["optimal_price"] = comp[["curve_price", "uni_price"]].min(axis=1)
    avg_optimal           = comp["optimal_price"].mean()

    always_curve   = calc_pnl(avg_curve,   amount_usd)
    always_uni     = calc_pnl(avg_uni,     amount_usd)
    optimal_route  = calc_pnl(avg_optimal, amount_usd)

    print(f"\n[Routing Strategy Comparison]  (based on full-period average VWAP)")
    print(f"  Hours Curve better   : {curve_wins}/{total_hours}h")
    print(f"  Hours Uniswap better : {uni_wins}/{total_hours}h")
    print(f"\n  Strategy                   avg fill price   return")
    print(f"  {'-'*48}")
    print(f"  A. Always Curve            ${always_curve['entry_price']:.4f}   {always_curve['gross_pnl_pct']:+.2f}%")
    print(f"  B. Always Uniswap          ${always_uni['entry_price']:.4f}   {always_uni['gross_pnl_pct']:+.2f}%")
    print(f"  C. Optimal per-hour route  ${optimal_route['entry_price']:.4f}   {optimal_route['gross_pnl_pct']:+.2f}%")
    improvement_vs_curve = optimal_route["gross_pnl_pct"] - always_curve["gross_pnl_pct"]
    print(f"\n  Optimal routing improvement (C vs A): {improvement_vs_curve:+.3f}%p")

    routing = {
        "always_curve":   always_curve,
        "always_uni":     always_uni,
        "optimal_route":  optimal_route,
        "curve_wins":     curve_wins,
        "uni_wins":       uni_wins,
        "peak_curve_pnl": curve_pnl,
        "peak_uni_pnl":   uni_pnl,
    }

    return {
        "comparison":   comp,
        "peak_summary": peak_window,
        "routing":      routing,
    }


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    svb_result  = run_comparison("svb",  amount_usd=50_000)
    usdt_result = run_comparison("usdt", amount_usd=50_000)

    print(f"\n{'='*68}")
    print("  Cross-Event Routing Improvement Comparison")
    print(f"{'='*68}")
    for name, res in [("SVB", svb_result), ("USDT", usdt_result)]:
        if not res:
            continue
        r = res["routing"]
        print(
            f"  {name:<5}  "
            f"Curve {r['curve_wins']}h / Uni {r['uni_wins']}h better  |  "
            f"Optimal routing improvement: "
            f"{r['optimal_route']['gross_pnl_pct'] - r['always_curve']['gross_pnl_pct']:+.3f}%p  |  "
            f"Peak better pool: "
            f"{'Uniswap' if r['peak_uni_pnl']['entry_price'] < r['peak_curve_pnl']['entry_price'] else 'Curve'}"
        )


# ── Backtest Results Summary ──────────────────────────────────────────────────
#
# ┌──────────────────────────────────────────────────────────────────────────┐
# │  SVB Crisis (2023-03-09 ~ 03-14)  |  USDT → USDC (buy cheap USDC)      │
# ├──────────────────────────────────────────────────────────────────────────┤
# │  [Peak Period Analysis]  peak hour = 2023-03-11 07:00:00                 │
# │  Pool: DAI 30.8% / USDC 44.0% / USDT 25.2%                             │
# │                                                                          │
# │  Peak ±2h window:                                                        │
# │  hour                    curve     uni    diff(bps)  better              │
# │  2023-03-11 05:00        0.9392  0.9960      -570    curve               │
# │  2023-03-11 06:00        0.9121  0.9972      -853    curve               │
# │  2023-03-11 07:00 ◀      0.8849  0.9958     -1114    curve               │
# │  2023-03-11 08:00        0.9012  0.9031       -21    curve               │
# │  2023-03-11 09:00        0.9130  0.9654      -543    curve               │
# │                                                                          │
# │  Peak fill prices:                                                       │
# │    Curve   : $0.8849  →  return +13.01%                                 │
# │    Uniswap : $0.9958  →  return  +0.42%                                 │
# │    Better pool   : Curve  (gap: 1114 bps)                               │
# │    Return delta  : -12.59%p  (Uniswap vs Curve at peak)                 │
# │                                                                          │
# │  [Routing Strategy Comparison]  (full period, 142h)                     │
# │  Hours Curve better: 92/142h  |  Hours Uniswap better: 50/142h         │
# │                                                                          │
# │  Strategy                   avg fill price   return                     │
# │  A. Always Curve            $0.9790   +2.15%                            │
# │  B. Always Uniswap          $0.9841   +1.62%                            │
# │  C. Optimal per-hour route  $0.9783   +2.22%                            │
# │                                                                          │
# │  Optimal routing improvement (C vs A): +0.070%p                         │
# │                                                                          │
# │  [Interpretation] Uniswap VWAP stayed near $0.99 at peak because only  │
# │  small-volume USDT→USDC trades occurred there (limited liquidity).      │
# │  Curve absorbed the bulk of depeg pressure, filling down to $0.88.     │
# │  At peak: Curve beats Uniswap by 1114 bps. Over the full period,       │
# │  Curve (+2.15%) also beats Uniswap (+1.62%). Routing optimization      │
# │  (+0.07%p) is real but tiny vs Strategy ② threshold selection           │
# │  (up to +6.5%p difference).                                             │
# └──────────────────────────────────────────────────────────────────────────┘
#
# ┌──────────────────────────────────────────────────────────────────────────┐
# │  USDT Depeg (2023-06-14 ~ 06-16)  |  USDC → USDT (buy cheap USDT)      │
# ├──────────────────────────────────────────────────────────────────────────┤
# │  [Peak Period Analysis]  peak hour = 2023-06-15 08:00:00                 │
# │  Pool: DAI 18.9% / USDC 17.7% / USDT 63.4%                             │
# │                                                                          │
# │  Peak ±2h window:                                                        │
# │  hour                    curve     uni    diff(bps)  better              │
# │  2023-06-15 06:00        0.9976  0.9971        +5    uniswap             │
# │  2023-06-15 07:00        0.9975  0.9971        +4    uniswap             │
# │  2023-06-15 08:00 ◀      0.9966  0.9967        -1    curve               │
# │  2023-06-15 09:00        0.9967  0.9950       +17    uniswap             │
# │  2023-06-15 10:00        0.9975  0.9966        +9    uniswap             │
# │                                                                          │
# │  Peak fill prices:                                                       │
# │    Curve   : $0.9966  →  return +0.34%                                  │
# │    Uniswap : $0.9967  →  return +0.33%                                  │
# │    Better pool   : Curve  (gap: 1.3 bps)                                │
# │    Return delta  : -0.01%p  (Uniswap vs Curve at peak)                  │
# │                                                                          │
# │  [Routing Strategy Comparison]  (full period, 67h)                      │
# │  Hours Curve better: 29/67h  |  Hours Uniswap better: 38/67h           │
# │                                                                          │
# │  Strategy                   avg fill price   return                     │
# │  A. Always Curve            $0.9991   +0.09%                            │
# │  B. Always Uniswap          $0.9990   +0.10%                            │
# │  C. Optimal per-hour route  $0.9990   +0.10%                            │
# │                                                                          │
# │  Optimal routing improvement (C vs A): +0.010%p                         │
# │                                                                          │
# │  [Interpretation] Both pools' VWAPs stayed within 1~2 bps throughout.  │
# │  Uniswap marginally better over the full period (38/67h) but the        │
# │  return difference is only 0.01%p. At peak, gap is just 1.3 bps.       │
# │  The USDT depeg was small ($0.004) — whether to enter at all matters   │
# │  far more than which pool to use.                                        │
# └──────────────────────────────────────────────────────────────────────────┘
#
# ── Overall Conclusion ────────────────────────────────────────────────────────
#
#  Across both events, Curve vs Uniswap routing optimization yields only
#  0.01~0.07%p improvement — negligible compared to typical gas costs
#  (0.05~0.2%), making aggregator routing economically questionable.
#
#  During large depegs like SVB, Curve dramatically outperforms Uniswap
#  (1114 bps gap at peak). Curve 3Pool's StableSwap design concentrates
#  depeg pressure, creating the largest price discrepancy — and the best
#  fill for informed traders. If using a single pool, Curve is optimal.
#  Even with an aggregator, maintaining high Curve allocation is near-optimal.
#
#  Key insight: Entry timing (threshold selection) drives returns far more
#  than pool routing. Focus on when to enter, not where.
